version: "3.7"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "AvenParking"
      MYSQL_DATABASE: "garbage_classifier"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123456"
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9100:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - "mysql"