version: "3.7"
services:
  backend:
    image: garbage_classifier
    build: .
    restart: always
    environment:
      - TZ=Asia/Taipei
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - "mariadb"

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "cxz123499"
      MARIADB_DATABASE: "garbage_classifier"
      MARIADB_USER: "test"
      MARIADB_PASSWORD: "123456"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:9100:80"
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - "mariadb"